language: php

sudo: required

php:
  - 7.3
  - 7.4
  - nightly
  - master

env:
  - TARANTOOL_VERSION=1.10
  - TARANTOOL_VERSION=2.0
  - TARANTOOL_VERSION=2.1

matrix:
  allow_failures:
    - php: nightly
    - php: master

services:
  - docker

before_script:
  - docker run -d --restart=always -p 3301:3301 --name tarantool progaudi/tarantool:$TARANTOOL_VERSION
  - docker run -d --restart=always -p 8123:8123 --name clickhouse yandex/clickhouse-server
  - composer self-update && composer global require hirak/prestissimo
  - composer install --no-interaction --prefer-source --optimize-autoloader

after_script:
  - if [[ -f coverage.clover ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
