language: php

sudo: required

php:
  - 7.4
  - nightly
  - master

env:
  - TARANTOOL_VERSION=1.10
  - TARANTOOL_VERSION=2.0
  - TARANTOOL_VERSION=2.1
  - TARANTOOL_VERSION=2.2

matrix:
  allow_failures:
    - php: nightly
    - php: master

services:
  - docker

before_script:
  - docker run -d --restart=always -p 3301:3301 --name tarantool progaudi/tarantool:$TARANTOOL_VERSION
  - docker run -d --restart=always -p 8123:8123 --name clickhouse yandex/clickhouse-server
  - composer install --no-interaction --optimize-autoloader

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

after_script:
  - if [[ -f coverage.clover ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
